services:
  goAIRA:
    image: goaira:latest
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
  vault:
    image: hashicorp/vault:latest
    build:
      args:
        UID: 1001
        GID: 1001
    pull_policy: always
    container_name: vault
    restart: always
    ports:
      - "8200:8200"  # Vault API port
    cap_add:
      - IPC_LOCK  # Prevent memory from being swapped to disk (security best practice)
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://vault:8200"
      VAULT_CLUSTER_ADDR: "http://vault:8201"
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{
            "tcp": {
              "address": "0.0.0.0:8200",
              "tls_disable": 1
            }
          }],
          "storage": {
            "file": {
              "path": "/vault/data"
            }
          },
          "ui": true
        }
    volumes:
      - vault_data:/vault/data  # Persistent storage
    command: server  # Start Vault in server mode

volumes:
  vault_data:
    driver: local
    

